// This file was auto-generated by ML.NET Model Builder. 

using System;
using Ml_net_solutionML.Model;

namespace Ml_net_solutionML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Longitude = -122.23F,
                Latitude = 37.88F,
                Housing_median_age = 41F,
                Total_rooms = 880F,
                Total_bedrooms = 129F,
                Population = 322F,
                Households = 126F,
                Median_income = 8.3252F,
                Ocean_proximity = @"NEAR BAY",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Median_house_value with predicted Median_house_value from sample data...\n\n");
            Console.WriteLine($"Longitude: {sampleData.Longitude}");
            Console.WriteLine($"Latitude: {sampleData.Latitude}");
            Console.WriteLine($"Housing_median_age: {sampleData.Housing_median_age}");
            Console.WriteLine($"Total_rooms: {sampleData.Total_rooms}");
            Console.WriteLine($"Total_bedrooms: {sampleData.Total_bedrooms}");
            Console.WriteLine($"Population: {sampleData.Population}");
            Console.WriteLine($"Households: {sampleData.Households}");
            Console.WriteLine($"Median_income: {sampleData.Median_income}");
            Console.WriteLine($"Ocean_proximity: {sampleData.Ocean_proximity}");
            Console.WriteLine($"\n\nPredicted Median_house_value: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
